# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: todo_reminder 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "todo_reminder"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Dillon Benson"]
  s.date = "2014-12-18"
  s.description = "Remind yourself of forgotten TO-DO's"
  s.email = "dillon.benson93@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "lib/todo_reminder.rb",
    "lib/todo_reminder/filehandler.rb",
    "lib/todo_reminder/manager.rb",
    "lib/todo_reminder/reminder.rb",
    "lib/todo_reminder/reminders/mac/say.rb",
    "lib/todo_reminder/scraper.rb",
    "lib/todo_reminder/todo.rb"
  ]
  s.homepage = "http://github.com/dillon-benson/todo_reminder"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Remind yourself of forgotten TO-DO's"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

